package com.hei.school.tessaproject.exception;

public enum ErrorCode {
    AUTH_EMAIL_ALREADY_EXISTS,
    AUTH_INVALID_TOKEN,
    AUTH_USER_NOT_FOUND,
    AUTH_NOT_FOUND,
    AUTH_TOO_MANY_ATTEMPTS,
    AUTH_UNAUTHORIZED_ACCESS,
    AUTH_TOKEN_NOT_FOUND,
    ACCESS_UNAUTHORIZED,
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,
    INTERNAL_SERVER_ERROR
}
